[workspace]
allow_dirty = true    # TODO: release-plz seems to otherwise complain about the submodules
release_always = true # TODO: reset to `false` when initial release has passed

[[package]]
name = "pindakaas"
publish_all_features = true

[[package]]
name = "pyndakaas"
publish = false
semver_check = false
