[package]
name = "pyndakaas"
description = "Python bindings for the pindakaas crate"
version = "0.5.1"
edition = "2021"

authors.workspace = true
license.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true

[lib]
name = "pindakaas"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.15"
pindakaas = { version = "0.5.1", path = "../pindakaas", features = ["kissat"] }
pyo3 = { version = "0.29.0", features = ["abi3-py39"] }

[lints]
workspace = true
