#ifndef pindakaas_h
#define pindakaas_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

int32_t add(int32_t a, int32_t b);

#endif /* pindakaas_h */
